export interface BaseEvent {
  type: EventBusName;
}

export interface BaseEventPayload<Payload> {
  type: EventBusName;
  payload: Payload;
}

export enum EventBusName {
  LOGOUT_EVENT,
  SEE_ANSWERS_TASK_EVENT,
  RESTART_TASK_EVENT,
  CHECK_SCORE_TASK_EVENT,
  SHOW_SIGNUP_EVENT,
  SHOW_TOAST_EVENT,
  SHOW_SIGNIN_EVENT,
  SHOW_UPDATE_PROFILE_EVENT,
  AUTH_SUCCESS_EVENT,
  UPDATE_PROFILE_SUCCESS_EVENT,
  SHOW_FORGOT_PASSWORD_EVENT,
  SHOW_CHANGE_PASSWORD_EVENT,
  SHOW_OTP_EVENT,
  NO_TOKEN_EVENT,
  FETCH_TOTAL_ORDER_EVENT,
  UPDATE_BACKGROUND_FEELING_EVENT,
  UPDATE_BACKGROUND_COURSE_EVENT,
  SHOW_MENU_MOBILE_EVENT,
  HIDE_MENU_MOBILE_EVENT,
  UPDATE_CART_LOCAL,
  UPDATE_COURSE_FAVORITE_LOCAL,
  UPDATE_TOTAL_COURSE_FAVORITE,
  UPDATE_DOCUMENT_FAVORITE_LOCAL,
  UPDATE_TOTAL_DOCUMENT_FAVORITE,
  SHOW_MODAL_AFTER_REGISTER_1,
  SHOW_MODAL_AFTER_REGISTER_2,
  SHOW_MODAL_AFTER_REGISTER_3,
  SHOW_MODAL_AFTER_REGISTER_4,
  SHOW_MODAL_COMING_SOON,
  SHOW_MODAL_REGISTER_TESTING,
  SHOW_MODAL_CHOOSE_TESTING,
  SHOW_MODAL_SCORE
}
