export const theme = {
  colors: {
    main: "#f4394f",
    primary: "#007bff",
    info: "#1890ff",
    success: "#52c41a",
    green: "#05C755",
    processing: "#1890ff",
    error: "#f5222d",
    highlight: "#f5222d",
    warning: "#faad14",
    normal: "#d9d9d9",
    background: "#f7f7f9",
    dark: "rgb(51,51,51)",
    text: "rgba(0, 0, 0, .65)",
    textSecondary: "rgba(0,0,0,.45)",
    borderBase: "hsv(0, 0, 85%)",
    borderSplit: "rgba(0, 0, 0, 0.05)",
    red: "red",
  },
  heights: {
    input: "48px",
    button: "49px",
  },
  borderRadius: {
    base: "4px",
    sm: "4px",
  },
  breakPoints: {
    breakSmall: "320px",
    breakMobile: "375px",
    breakMobileLarge: "414px",
    breakMobileMax: "480px",
    breakMobileMedium: "575px",
    breakTablet: "768px",
  },
  widths: {
    wide_650: "650px",
    wide_700: "700px",
    wide_900: "900px",
    wide_1110: "1110px",
  },
  family: {
    font: `"Chinese Quote", -apple-system, BlinkMacSystemFont, "Segoe UI", "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", "Helvetica Neue", Helvetica, Arial, sans-serif,
        "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"`,
    code: `"Anonymous Pro", "SFMono-Regular", Consolas, "Liberation Mono", Menlo, Courier, monospace`,
  },
  menu: {
    inlineTopLevelItemHeight: "36px",
    itemHeight: "36px",
  },
  header: {
    background: "#ffffff",
    height: "60px",
  },
  card: {
    paddingBase: "16px",
    paddingWider: "16px",
  },
};
